### ISSUE TITLE
In Routing Form, add Rule button is not working

### ISSUE THREAD

**Issue by AK-Ammo** [onehashai/onehash-cal#150]
![scrnli_8_9_2024_11-49-09 AM](https://github.com/user-attachments/assets/9f04e817-3d28-4de2-9ad7-235b9e08a961)

**Comment by AK-Ammo** [comment]
@Arjun3492 ,Kindly look into.

**Comment by Arjun3492** [comment]
solved with 2c80c235b5224a9d3ceb4d079825653cfe72d114
