### ISSUE TITLE
Not able to Install Hubspot CRM in OneHash Cal

### ISSUE THREAD

**Issue by AK-Ammo** [onehashai/onehash-cal#153]
![scrnli_8_22_2024_11-35-54 AM](https://github.com/user-attachments/assets/6f4f6125-86f6-4171-ba1f-1255608aeabd)

**Comment by AK-Ammo** [comment]
@Arjun3492 Kindly check

**Comment by Arjun3492** [comment]
Fixed in commit https://github.com/onehashai/onehash-cal/commit/72a58c6ef73e36476d2d41a4a983696ed17dec1f
