### ISSUE TITLE
Owner's or Admin's are not able to approve an unconfirmed meeting

### ISSUE THREAD

**Issue by manasOH** [onehashai/onehash-cal#156]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Owners or Admins are not able to approve an unconfirmed meeting

### Steps to Reproduce

1. Add an admin or owner in team
2. Create a collective scheduling event 
3. Enable require confirmation from the Advance setting

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- Only **creator owner** is able to confirm the meeting.

### Expected Results

- An owner or Admin should have requisite privilege.

**Comment by mr-loop-1** [comment]
I am looking to contribute and would want to work on this issue. Can you assign this to me.

**Comment by Arjun3492** [comment]
Solved with commit 2c80c235b5224a9d3ceb4d079825653cfe72d114
