### ISSUE TITLE
Password not visible while deleting the account.

### ISSUE THREAD

**Issue by AK-Ammo** [onehashai/onehash-cal#29]
![Screenshot (471)](https://github.com/onehashai/onehash-cal/assets/130673651/a4d6d8a5-e5cd-41af-9b90-80c591cf8092)

This is the case not just on one account but on multiple.

**Comment by AK-Ammo** [comment]
![Screenshot (473)](https://github.com/onehashai/onehash-cal/assets/130673651/13f0a681-b126-4ecc-ba6f-836e6299d6bb)
![Screenshot (472)](https://github.com/onehashai/onehash-cal/assets/130673651/b59e2df7-4df4-4404-8fc0-9e7674f09ab8)

On 90% screen, password field is visible but not on 100%

**Comment by onehash-ai** [comment]
Native Screen Issue to Individual
