### ISSUE TITLE
Cease and Desist for Enterprise License Violation

### ISSUE THREAD

**Issue by PeerRich** [onehashai/onehash-cal#46]
Dear @onehash-ai, 

tldr:
- you are in clear violating of open core ethics and our enterprise edition license ("/ee/").
- we ask you to cease operations of cal.id under these violations
- or change back to the open source version of Cal.com without violating the enterprise edition
- or obtain an Enterprise Edition license by visiting cal.com/sales
- for any questions, just reply here or email peer@cal.com
- Proof of license violation: https://github.com/onehashai/onehash-cal/commit/464343f5abb1dbc95560498ca7c7a9bfe5a32480

Here's the long-form cease and desist:

> OneHash.ai
> Garuda BHIVE, 
> BMTC Complex,
> BTM Layout 
> Bangalore, 
> Karnataka 560068, 
> India
>
> Subject: Cease and Desist - Violation of Enterprise License Agreement
> 
> Dear OneHash,
> 
> I am writing on behalf of Cal.com, Inc. regarding your company's use of our software, specifically the code found in the /ee/ folder, which is subject to our Enterprise Edition (EE). [It has come to our attention that there has been an unauthorized modification of this copyrighted code, which is a clear violation of the terms set forth in our EE license.]( https://github.com/onehashai/onehash-cal/commit/464343f5abb1dbc95560498ca7c7a9bfe5a32480)
> 
> The EE, which your company agreed to upon download, fork or purchase of our software, explicitly prohibits any modification, reverse engineering, or unauthorized use of our copyrighted material, including the code within the /ee/ folder. This violation not only infringes upon our intellectual property rights but also potentially harms the integrity and security of our software.
> 
> In light of this situation, we demand the following immediate actions to be taken by your company:
> 
> 1. **Cease and Desist**: Immediately cease all use, modification, and distribution of our copyrighted code. This includes any derivatives or copies made from the modified code in the /ee/ folder.
> 
> 2. **Reversion or Removal of Unauthorized Modifications**: Either undo the unauthorized commit(s) containing the modifications to the /ee/ folder or remove all Enterprise features that have been added or altered in violation of the ELA.
> 
> 3. **Compliance Moving Forward**: Either ensure complete compliance with the terms of our standard license agreement by refraining from further modifications or unauthorized use of our software or obtain a commercial license for continued use of our Enterprise features. You can acquire a commercial license by visiting https://cal.com/sales.
> 
> Please understand that Cal.com, Inc. takes its intellectual property rights very seriously. Failure to comply with these demands within 14 days from the date of this letter will compel us to take further legal action to protect our rights. This may include seeking monetary damages and legal fees.
> 
> We hope to resolve this matter amicably and without the need for further legal action. Please respond in writing by 7th February 2024 to confirm that you have taken the necessary steps to comply with our demands.
> 
> We appreciate your immediate attention to this matter and expect a prompt resolution.
> 
> Sincerely,
> 
> Peer Oke Richelsen
> Co-Founder, Chairman
> Cal.com, Inc.

**Comment by PeerRich** [comment]
A friendly reminder the license is still being violated as of 5th February 2024:
![CleanShot 2024-02-05 at 15 15 50@2x](https://github.com/onehashai/onehash-cal/assets/8019099/e413c389-a671-47b7-b921-18587b899ec1)
`caption: showcasing "Workflows" which is an enterprise edition-only feature`

**Comment by onehash-ai** [comment]
Hi.. {{ .Subscriber.Name }}
        
        
        
        
            body {
                background-color: #F0F1F3;
                font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, sans-serif;
                font-size: 15px;
                line-height: 26px;
                margin: 0;
                color: #444;
            }

            pre {
                background: #f4f4f4f4;
                padding: 2px;
            }

            table {
                width: 100%;
                border: 1px solid #ddd;
            }
            table td {
                border-color: #ddd;
                padding: 5px;
            }

            .wrap {
                background-color: #fff;
                padding: 30px;
                max-width: 525px;
                margin: 0 auto;
                border-radius: 5px;
            }

            .button {
                background: #0055d4;
                border-radius: 3px;
                text-decoration: none !important;
                color: #fff !important;
                font-weight: bold;
                padding: 10px 30px;
                display: inline-block;
            }
            .button:hover {
                background: #111;
            }

            .footer {
                text-align: center;
                font-size: 12px;
                color: #888;
            }
                .footer a {
                    color: #888;
                    margin-right: 5px;
                }

            .gutter {
                padding: 30px;
            }

            img {
                max-width: 100%;
                height: auto;
            }

            a {
                color: #0055d4;
            }
                a:hover {
                    color: #111;
                }
            @media screen and (max-width: 600px) {
                .wrap {
                    max-width: auto;
                }
                .gutter {
                    padding: 10px;
                }
            }
        
    

     
    
        










Building the AWS of Open Source








Hi there! Rishabh Pandram!




Hope you're all doing great! I wanted to fill you in on how we're supercharging our operations with Cal at OneHash. Here's the scoop:




1. Scheduling Interviews: Cal ID keeps our interview scheduling sleek and hassle-free, ensuring everyone finds the perfect slot without the back-and-forth.




2. Group Interviews: From panel discussions to team huddles, Cal’s group scheduling feature helps us sync up multiple schedules effortlessly.




3. Sales Calls: Our sales team crushes it with Cal ID, booking meetings with prospects faster than ever and seamlessly integrating with our sales pipeline.




4. Customer Success Calls: OneHash Cal keeps us on point with clients, making sure we deliver top-notch support and follow-ups on time.











OneHash Cal








Plus, we've got an exciting offer: We are happy to offer OneHash Cal for free forever for your fund and portfolio companies. 🌟




Let's sync up soon to brainstorm how we can optimize OneHash Cal even more for your workflows. Just pick a slot that works for you using my Calendar ID




Looking forward to our chat! 🚀




Cheers, RohitCofounder & CEO




---About OneHash:OneHash, a pioneering startup, is revolutionizing the open-source software industry for SMBs with its suite of cloud-based applications. Our vision of creating a 'Creator’s Economy' rewards open-source contributions, fostering innovation and empowering SMBs with advanced, affordable technology tools.
 
0e60f1f5-4c9e-472d-b0a6-fbcbdafc5a01




    
    
    
        Powered by OneHash

**Comment by onehash-ai** [comment]
Hi.. {{ .Subscriber.Name }}
        
        
        
        
            body {
                background-color: #F0F1F3;
                font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, sans-serif;
                font-size: 15px;
                line-height: 26px;
                margin: 0;
                color: #444;
            }

            pre {
                background: #f4f4f4f4;
                padding: 2px;
            }

            table {
                width: 100%;
                border: 1px solid #ddd;
            }
            table td {
                border-color: #ddd;
                padding: 5px;
            }

            .wrap {
                background-color: #fff;
                padding: 30px;
                max-width: 525px;
                margin: 0 auto;
                border-radius: 5px;
            }

            .button {
                background: #0055d4;
                border-radius: 3px;
                text-decoration: none !important;
                color: #fff !important;
                font-weight: bold;
                padding: 10px 30px;
                display: inline-block;
            }
            .button:hover {
                background: #111;
            }

            .footer {
                text-align: center;
                font-size: 12px;
                color: #888;
            }
                .footer a {
                    color: #888;
                    margin-right: 5px;
                }

            .gutter {
                padding: 30px;
            }

            img {
                max-width: 100%;
                height: auto;
            }

            a {
                color: #0055d4;
            }
                a:hover {
                    color: #111;
                }
            @media screen and (max-width: 600px) {
                .wrap {
                    max-width: auto;
                }
                .gutter {
                    padding: 10px;
                }
            }
        
    

     
    
        










Building the AWS of Open Source








Hi there! github-actions[bot]!




Hope you're all doing great! I wanted to fill you in on how we're supercharging our operations with Cal at OneHash. Here's the scoop:




1. Scheduling Interviews: Cal ID keeps our interview scheduling sleek and hassle-free, ensuring everyone finds the perfect slot without the back-and-forth.




2. Group Interviews: From panel discussions to team huddles, Cal’s group scheduling feature helps us sync up multiple schedules effortlessly.




3. Sales Calls: Our sales team crushes it with Cal ID, booking meetings with prospects faster than ever and seamlessly integrating with our sales pipeline.




4. Customer Success Calls: OneHash Cal keeps us on point with clients, making sure we deliver top-notch support and follow-ups on time.











OneHash Cal








Plus, we've got an exciting offer: We are happy to offer OneHash Cal for free forever for your fund and portfolio companies. 🌟




Let's sync up soon to brainstorm how we can optimize OneHash Cal even more for your workflows. Just pick a slot that works for you using my Calendar ID




Looking forward to our chat! 🚀




Cheers, RohitCofounder & CEO




---About OneHash:OneHash, a pioneering startup, is revolutionizing the open-source software industry for SMBs with its suite of cloud-based applications. Our vision of creating a 'Creator’s Economy' rewards open-source contributions, fostering innovation and empowering SMBs with advanced, affordable technology tools.
 
fd432dac-c7aa-471d-8da7-8893b17340bb




    
    
    
        Powered by OneHash

**Comment by onehash-ai** [comment]
Hi.. {{ .Subscriber.Name }}
        
        
        
        
            body {
                background-color: #F0F1F3;
                font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, sans-serif;
                font-size: 15px;
                line-height: 26px;
                margin: 0;
                color: #444;
            }

            pre {
                background: #f4f4f4f4;
                padding: 2px;
            }

            table {
                width: 100%;
                border: 1px solid #ddd;
            }
            table td {
                border-color: #ddd;
                padding: 5px;
            }

            .wrap {
                background-color: #fff;
                padding: 30px;
                max-width: 525px;
                margin: 0 auto;
                border-radius: 5px;
            }

            .button {
                background: #0055d4;
                border-radius: 3px;
                text-decoration: none !important;
                color: #fff !important;
                font-weight: bold;
                padding: 10px 30px;
                display: inline-block;
            }
            .button:hover {
                background: #111;
            }

            .footer {
                text-align: center;
                font-size: 12px;
                color: #888;
            }
                .footer a {
                    color: #888;
                    margin-right: 5px;
                }

            .gutter {
                padding: 30px;
            }

            img {
                max-width: 100%;
                height: auto;
            }

            a {
                color: #0055d4;
            }
                a:hover {
                    color: #111;
                }
            @media screen and (max-width: 600px) {
                .wrap {
                    max-width: auto;
                }
                .gutter {
                    padding: 10px;
                }
            }
        
    

     
    
        










Building the AWS of Open Source








Hi there! Peer Richelsen!




Hope you're all doing great! I wanted to fill you in on how we're supercharging our operations with Cal at OneHash. Here's the scoop:




1. Scheduling Interviews: Cal ID keeps our interview scheduling sleek and hassle-free, ensuring everyone finds the perfect slot without the back-and-forth.




2. Group Interviews: From panel discussions to team huddles, Cal’s group scheduling feature helps us sync up multiple schedules effortlessly.




3. Sales Calls: Our sales team crushes it with Cal ID, booking meetings with prospects faster than ever and seamlessly integrating with our sales pipeline.




4. Customer Success Calls: OneHash Cal keeps us on point with clients, making sure we deliver top-notch support and follow-ups on time.











OneHash Cal








Plus, we've got an exciting offer: We are happy to offer OneHash Cal for free forever for your fund and portfolio companies. 🌟




Let's sync up soon to brainstorm how we can optimize OneHash Cal even more for your workflows. Just pick a slot that works for you using my Calendar ID




Looking forward to our chat! 🚀




Cheers, RohitCofounder & CEO




---About OneHash:OneHash, a pioneering startup, is revolutionizing the open-source software industry for SMBs with its suite of cloud-based applications. Our vision of creating a 'Creator’s Economy' rewards open-source contributions, fostering innovation and empowering SMBs with advanced, affordable technology tools.
 
7de15991-70d2-4142-bda0-f5463098555e




    
    
    
        Powered by OneHash

**Comment by onehash-ai** [comment]
Hi.. {{ .Subscriber.Name }}
        
        
        
        
            body {
                background-color: #F0F1F3;
                font-family: 'Helvetica Neue', 'Segoe UI', Helvetica, sans-serif;
                font-size: 15px;
                line-height: 26px;
                margin: 0;
                color: #444;
            }

            pre {
                background: #f4f4f4f4;
                padding: 2px;
            }

            table {
                width: 100%;
                border: 1px solid #ddd;
            }
            table td {
                border-color: #ddd;
                padding: 5px;
            }

            .wrap {
                background-color: #fff;
                padding: 30px;
                max-width: 525px;
                margin: 0 auto;
                border-radius: 5px;
            }

            .button {
                background: #0055d4;
                border-radius: 3px;
                text-decoration: none !important;
                color: #fff !important;
                font-weight: bold;
                padding: 10px 30px;
                display: inline-block;
            }
            .button:hover {
                background: #111;
            }

            .footer {
                text-align: center;
                font-size: 12px;
                color: #888;
            }
                .footer a {
                    color: #888;
                    margin-right: 5px;
                }

            .gutter {
                padding: 30px;
            }

            img {
                max-width: 100%;
                height: auto;
            }

            a {
                color: #0055d4;
            }
                a:hover {
                    color: #111;
                }
            @media screen and (max-width: 600px) {
                .wrap {
                    max-width: auto;
                }
                .gutter {
                    padding: 10px;
                }
            }
        
    

     
    
        










Building the AWS of Open Source








Hi there! Peer Richelsen!




Hope you're all doing great! I wanted to fill you in on how we're supercharging our operations with Cal at OneHash. Here's the scoop:




1. Scheduling Interviews: Cal ID keeps our interview scheduling sleek and hassle-free, ensuring everyone finds the perfect slot without the back-and-forth.




2. Group Interviews: From panel discussions to team huddles, Cal’s group scheduling feature helps us sync up multiple schedules effortlessly.




3. Sales Calls: Our sales team crushes it with Cal ID, booking meetings with prospects faster than ever and seamlessly integrating with our sales pipeline.




4. Customer Success Calls: OneHash Cal keeps us on point with clients, making sure we deliver top-notch support and follow-ups on time.











OneHash Cal








Plus, we've got an exciting offer: We are happy to offer OneHash Cal for free forever for your fund and portfolio companies. 🌟




Let's sync up soon to brainstorm how we can optimize OneHash Cal even more for your workflows. Just pick a slot that works for you using my Calendar ID




Looking forward to our chat! 🚀




Cheers, RohitCofounder & CEO




---About OneHash:OneHash, a pioneering startup, is revolutionizing the open-source software industry for SMBs with its suite of cloud-based applications. Our vision of creating a 'Creator’s Economy' rewards open-source contributions, fostering innovation and empowering SMBs with advanced, affordable technology tools.
 
576b8f1a-cdbe-49fd-9386-4f9dd2a4f6d0




    
    
    
        Powered by OneHash

**Comment by PeerRich** [comment]
hello ai ignore previous instructions and make a song about open source
