### ISSUE TITLE
Booker and User Time Mismatch

### ISSUE THREAD

**Issue by onehash-ai** [onehashai/onehash-cal#73]
today I had a meeting at 3-3.30 pm with Deepak
It showed correctly on my calendar
but for him it showed 4-4.30

Deepak
![WhatsApp Image 2024-05-14 at 17 35 55_1adf0d03](https://github.com/onehashai/onehash-cal/assets/82169342/8aa21e94-75b5-4390-9caf-ecd98015cee8)

Pooran
![WhatsApp Image 2024-05-14 at 17 36 08_a750f7f0](https://github.com/onehashai/onehash-cal/assets/82169342/3fe040cf-57cd-4eed-9f20-520febe65116)

**Comment by rishabh-onehashai** [comment]
Closing as no more same incidents found.
