### ISSUE TITLE
Unable to create new workflow or edit the existing workflow

### ISSUE THREAD

**Issue by manasOH** [onehashai/onehash-cal#92]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Unable to create new workflow or edit the existing workflow

### Steps to Reproduce

1. Click on new or edit workflow

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- Getting a blank screen. 

### Expected Results

- Should be able to create or edit workflow.

### Evidence

<img width="1430" alt="image" src="https://github.com/onehashai/onehash-cal/assets/142008405/84051087-72c8-4108-b6ad-8bdc319e06d8">

**Comment by rishabh-onehashai** [comment]
@manasOH The issue has been fixed
